

PLOT_CLUSTERS_COFIG_SPACE = 1;
SAVE_CLUSTERS_COFIG_SPACE = 0;

if PLOT_CLUSTERS_COFIG_SPACE == 0
    SAVE_CLUSTERS_COFIG_SPACE = 0;
end

PLOT_RESULT_WORK_SPACE = 1;
SAVE_RESULT_WORK_SPACE = 0;

if PLOT_RESULT_WORK_SPACE == 0
    SAVE_RESULT_WORK_SPACE = 0;
end

CLUSTERING_METHOD = 2; % 1 : k-means, 2 : MeanShift
DRAW_NAVI_WORKSPACE = 0;
SAVE_NAVI_WORKSPACE = 0;

VORNOI_PLOT_TRIGGER = 1;
VORNOI_COMPUTE = 0;

if DRAW_NAVI_WORKSPACE == 1
    VORNOI_PLOT_TRIGGER = 1;
end
if VORNOI_PLOT_TRIGGER == 1
    VORNOI_COMPUTE = 1;    
    DRAW_NAVI_WORKSPACE = 1;

end
